DROP TABLE IF EXISTS car;

CREATE TABLE Car(
  id VARCHAR(250) PRIMARY KEY,
  make VARCHAR(250) NOT NULL,
  model VARCHAR(250) NOT NULL,
  colour VARCHAR(250) DEFAULT NULL,
  year INT,
  sounds_like VARCHAR(250) DEFAULT NULL);